name: Build Docker Image

on:
  push

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t public-api:latest .

      - name: Save Docker image as tar artifact
        run: docker save -o image.tar public-api:latest

      - name: Upload image artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: image.tar
