name: Build Docker Image and Generate Artifact

on:
  push

jobs:
  build-and-generate-artifact:
    runs-on: [self-hosted]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t fast-api:latest .
          docker buildx build --platform linux/arm64 -t fast-api:latest .

      - name: Save Docker image as tarball
        run: |
          docker save fast-api:latest -o docker-image.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: ./docker-image.tar
